# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87831526a76468e81dae2c9495318f19c0bb0c0217d6669a97a62ae27ebe89ecdf27b488b1d142a37e7753d253d0d22a4618708f21580364c9658bc872fd1227

test:
  secret_key_base: 512d12e50f1c34c71f5c96049fc4a7024c531d3af5ab531d4e1f9bee8665c707e8b11c822d4812eb8a21f9766f4e8fe56975a0c5697bdd8a6e65e54c814aee3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
